"""POST /conversations/{conversation_id}/fork — branch a Conversation.

Two modes (user-stories.md #14):
  keep_messages      new Conversation seeded with messages 1..N copied
                     (assistant rows carry their active variant only).
  summarize_fresh    new Conversation empty + parent_branch_summary
                     generated by the Text Engine provider. Summary is
                     injected at prompt position #10 going forward.

Per creator-vision.md §5.2 + domain.md §6 #6 the child is self-contained:
lorebook_entries and grammar_corrections rows in the kept range are
COPIED (not referenced) with the new conversation_id.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Literal

import httpx
from fastapi import APIRouter, Depends, Header, HTTPException, status
from pydantic import BaseModel, Field

from ..deps.jwt import AuthUser, verify_supabase_jwt
from ..deps.supabase import UserSupabase

router = APIRouter()

SUPABASE_ANON_KEY = os.environ.get("SUPABASE_ANON_KEY", "")
_BRANCH_SUMMARY_SYSTEM = (Path(__file__).parent.parent / "prompts" / "branch_summary_system.txt").read_text().strip()


class ForkPayload(BaseModel):
    message_id: str
    mode: Literal["keep_messages", "summarize_fresh"]
    title: str | None = Field(default=None, max_length=200)


def _user_client(authorization: str) -> UserSupabase:
    scheme, _, token = authorization.partition(" ")
    if scheme.lower() != "bearer" or not token.strip():
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Missing bearer token")
    if not SUPABASE_ANON_KEY:
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "SUPABASE_ANON_KEY not configured")
    return UserSupabase(jwt=token.strip(), apikey=SUPABASE_ANON_KEY)


async def _generate_branch_summary(
    provider: dict,
    api_key: str,
    transcript: list[dict[str, str]],
    parent_title: str,
) -> tuple[str, str]:
    """Call the Text Engine provider for a TITLE + body summary.

    Returns (title, summary_body). Falls back gracefully: TITLE line missing
    → title = "Branch of {parent_title}"; empty transcript → short canned
    summary.
    """
    transcript_text = "\n\n".join(
        f"{m['role'].upper()}: {m['content']}" for m in transcript if m.get("content")
    ).strip()
    chat_messages: list[dict[str, str]] = [
        {"role": "system", "content": _BRANCH_SUMMARY_SYSTEM},
        {"role": "user", "content": transcript_text or "(no prior messages)"},
    ]

    url = (provider.get("base_url") or "").rstrip("/") + "/chat/completions"
    payload = {
        "model": provider.get("model_id") or "",
        "messages": chat_messages,
        "temperature": 0.3,
        "max_tokens": 400,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(url, headers=headers, json=payload)
        if resp.status_code != 200:
            body = resp.text[:500]
            raise HTTPException(status.HTTP_502_BAD_GATEWAY, f"summary provider error {resp.status_code}: {body}")
        data = resp.json()
    content = (data.get("choices") or [{}])[0].get("message", {}).get("content") or ""
    content = content.strip()

    title = f"Branch of {parent_title}"
    body = content
    if content.upper().startswith("TITLE:"):
        first_line, _, rest = content.partition("\n")
        parsed_title = first_line.split(":", 1)[1].strip()
        if parsed_title:
            title = parsed_title[:200]
        body = rest.strip()
    return title, body


@router.post("/conversations/{conversation_id}/fork")
async def fork_conversation(
    conversation_id: str,
    payload: ForkPayload,
    user: AuthUser = Depends(verify_supabase_jwt),
    authorization: str = Header(..., alias="Authorization"),
) -> dict:
    """Fork the conversation atomically (review #1).

    The whole copy (child conversation + messages + variants +
    lorebook + grammar) runs inside `fork_conversation_tx`, a single
    SECURITY DEFINER SQL function → either all rows land or none do.
    The only step that must stay in Python is the summarize-fresh
    LLM call, whose output is passed to the RPC as a string.
    """
    del user  # user id is enforced by auth.uid() inside the RPC
    sup = _user_client(authorization)

    async with httpx.AsyncClient(timeout=60.0) as client:
        # Resolve parent title + generate summary BEFORE the transactional
        # RPC so any failure here surfaces as an HTTP error without a
        # half-written child row.
        convs = await sup.select(client, "conversations", {
            "select": "id,title",
            "id": f"eq.{conversation_id}",
            "limit": "1",
        })
        if not convs:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "conversation not found")
        parent_title = convs[0].get("title") or "Conversation"

        child_title = (payload.title or "").strip()
        parent_branch_summary: str | None = None

        if payload.mode == "summarize_fresh":
            providers = await sup.select(client, "provider_configs", {
                "select": "*",
                "kind": "eq.text",
                "is_active": "eq.true",
                "limit": "1",
            })
            if not providers:
                raise HTTPException(status.HTTP_409_CONFLICT, "no active text provider — configure one in Settings → Text Engine")
            provider = providers[0]
            api_key = await sup.rpc(client, "get_active_text_key")
            if not api_key:
                raise HTTPException(status.HTTP_409_CONFLICT, "active provider has no stored key")

            # Kept-range transcript for the summary. Only needed in this
            # mode; the keep_messages path doesn't read anything here.
            anchor_rows = await sup.select(client, "messages", {
                "select": "created_at",
                "id": f"eq.{payload.message_id}",
                "conversation_id": f"eq.{conversation_id}",
                "limit": "1",
            })
            if not anchor_rows:
                raise HTTPException(status.HTTP_404_NOT_FOUND, "anchor message not found in conversation")
            kept = await sup.select(client, "messages", {
                "select": "id,role,text,active_variant_id,created_at",
                "conversation_id": f"eq.{conversation_id}",
                "created_at": f"lte.{anchor_rows[0]['created_at']}",
                "order": "created_at.asc",
            })
            assistant_variant_ids = [m["active_variant_id"] for m in kept
                                     if m["role"] == "assistant" and m["active_variant_id"]]
            variant_content: dict[str, str] = {}
            if assistant_variant_ids:
                vs = await sup.select(client, "message_variants", {
                    "select": "id,content",
                    "id": f"in.({','.join(assistant_variant_ids)})",
                })
                variant_content = {v["id"]: v["content"] for v in vs}

            transcript: list[dict[str, str]] = []
            for m in kept:
                if m["role"] == "user":
                    if m.get("text"):
                        transcript.append({"role": "user", "content": m["text"]})
                elif m["role"] == "assistant":
                    active = m.get("active_variant_id")
                    if active and active in variant_content:
                        transcript.append({"role": "assistant", "content": variant_content[active]})

            parsed_title, parent_branch_summary = await _generate_branch_summary(
                provider, api_key, transcript, parent_title,
            )
            if not child_title:
                child_title = parsed_title

        if not child_title:
            child_title = f"Branch of {parent_title}"

        # Atomic copy.
        try:
            child_id = await sup.rpc(client, "fork_conversation_tx", {
                "p_parent_conversation_id": conversation_id,
                "p_anchor_message_id": payload.message_id,
                "p_mode": payload.mode,
                "p_title": child_title,
                "p_parent_branch_summary": parent_branch_summary,
            })
        except httpx.HTTPStatusError as exc:
            # Surface the RPC's error code (P0002 = not found) as a 404 where
            # applicable; everything else as 500 (handled by global handler).
            msg = exc.response.text[:300] if exc.response is not None else str(exc)
            if "conversation not found" in msg or "anchor message" in msg:
                raise HTTPException(status.HTTP_404_NOT_FOUND, msg) from exc
            raise

        if not isinstance(child_id, str):
            raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "fork_conversation_tx returned invalid id")

        return {"conversation_id": child_id, "title": child_title, "branch_mode": payload.mode}
