/**
 * Cycle 0024 — Import Backup.
 * Reads a .zip (generated by dataExport), parses each JSON file,
 * and upserts rows into the user's account via supabase-js.
 * Existing rows with matching IDs are skipped (no overwrite).
 */

import JSZip from "jszip";
import { supabase } from "./supabase";

export type ImportResult = {
  characters: number;
  conversations: number;
  messages: number;
  personas: number;
  lorebook: number;
  errors: string[];
};

export async function importBackup(file: File, userId: string): Promise<ImportResult> {
  const zip = await JSZip.loadAsync(file);
  const result: ImportResult = {
    characters: 0, conversations: 0, messages: 0,
    personas: 0, lorebook: 0, errors: [],
  };

  // 1. Characters
  const charsFile = zip.file("characters.json");
  if (charsFile) {
    try {
      const chars = JSON.parse(await charsFile.async("text")) as Record<string, unknown>[];
      for (const c of chars) {
        const row: Record<string, unknown> = { ...c, user_id: userId };
        delete row.created_at;
        delete row.updated_at;
        const { error } = await supabase.from("characters").upsert(row, { onConflict: "id" });
        if (error) result.errors.push(`character ${c.id}: ${error.message}`);
        else result.characters++;
      }
    } catch (e) { result.errors.push(`characters.json: ${e}`); }
  }

  // 2. Conversations + messages + variants
  const convsFile = zip.file("conversations.json");
  if (convsFile) {
    try {
      const convs = JSON.parse(await convsFile.async("text")) as Record<string, unknown>[];
      for (const conv of convs) {
        const messages = (conv.messages ?? []) as Record<string, unknown>[];
        const variants = (conv.variants ?? []) as Record<string, unknown>[];

        // Insert conversation (skip nested fields)
        const convRow: Record<string, unknown> = { ...conv, user_id: userId };
        delete convRow.messages;
        delete convRow.variants;
        delete convRow.created_at;
        delete convRow.updated_at;
        const { error: convErr } = await supabase.from("conversations").upsert(convRow, { onConflict: "id" });
        if (convErr) { result.errors.push(`conversation ${conv.id}: ${convErr.message}`); continue; }
        result.conversations++;

        // Insert messages
        for (const m of messages) {
          const msgRow = { ...m };
          delete msgRow.created_at;
          delete msgRow.updated_at;
          const { error } = await supabase.from("messages").upsert(msgRow, { onConflict: "id" });
          if (error) result.errors.push(`message ${m.id}: ${error.message}`);
          else result.messages++;
        }

        // Insert variants
        for (const v of variants) {
          const varRow = { ...v };
          delete varRow.created_at;
          const { error } = await supabase.from("message_variants").upsert(varRow, { onConflict: "id" });
          if (error) result.errors.push(`variant ${v.id}: ${error.message}`);
        }
      }
    } catch (e) { result.errors.push(`conversations.json: ${e}`); }
  }

  // 3. Personas
  const personasFile = zip.file("personas.json");
  if (personasFile) {
    try {
      const personas = JSON.parse(await personasFile.async("text")) as Record<string, unknown>[];
      for (const p of personas) {
        const row: Record<string, unknown> = { ...p, user_id: userId };
        delete row.created_at;
        delete row.updated_at;
        const { error } = await supabase.from("user_personas").upsert(row, { onConflict: "id" });
        if (error) result.errors.push(`persona ${p.id}: ${error.message}`);
        else result.personas++;
      }
    } catch (e) { result.errors.push(`personas.json: ${e}`); }
  }

  // 4. Lorebook
  const lorebookFile = zip.file("lorebook.json");
  if (lorebookFile) {
    try {
      const entries = JSON.parse(await lorebookFile.async("text")) as Record<string, unknown>[];
      for (const entry of entries) {
        const row: Record<string, unknown> = { ...entry, user_id: userId };
        delete row.created_at;
        delete row.updated_at;
        const { error } = await supabase.from("lorebook_entries").upsert(row, { onConflict: "id" });
        if (error) result.errors.push(`lorebook ${entry.id}: ${error.message}`);
        else result.lorebook++;
      }
    } catch (e) { result.errors.push(`lorebook.json: ${e}`); }
  }

  // 5. Settings (merge, don't overwrite — user may have changed prefs since export)
  const settingsFile = zip.file("settings.json");
  if (settingsFile) {
    try {
      const importedPrefs = JSON.parse(await settingsFile.async("text"));
      const { data: currentRow } = await supabase.from("users").select("preferences").eq("id", userId).single();
      const current = (currentRow?.preferences ?? {}) as Record<string, unknown>;
      const merged = { ...importedPrefs, ...current }; // current wins on conflict
      await supabase.from("users").update({ preferences: merged }).eq("id", userId);
    } catch (e) { result.errors.push(`settings.json: ${e}`); }
  }

  return result;
}
