-- Cycle 0014 — generated_images + inline_media + generated-media bucket
-- + image-provider BYOK RPCs.
-- Satisfies schema.md §2.11, §2.16; creator-vision.md §5.5, §7, §8;
-- user-stories.md #44 (ComfyUI config), #46 (Character avatar), #50
-- (generate image from assistant reply).

create type public.media_kind as enum ('image', 'video');

create table public.generated_images (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.users(id) on delete cascade,
  character_id        uuid not null references public.characters(id) on delete cascade,
  conversation_id     uuid references public.conversations(id) on delete set null,
  message_id          uuid references public.messages(id) on delete set null,
  kind                public.media_kind not null default 'image',
  prompt              text not null,
  refined_prompt      text,
  resolution_preset   text not null default 'square_1024',
  dimensions          jsonb not null default '{"w":1024,"h":1024}'::jsonb,
  provider_snapshot   jsonb not null default '{}'::jsonb,
  seed                bigint,
  storage_ref         text,
  sfw_blocked         boolean not null default false,
  favorite            boolean not null default false,
  created_at          timestamptz not null default now()
);

alter table public.generated_images enable row level security;

create policy generated_images_select_own on public.generated_images
  for select using (user_id = auth.uid());
create policy generated_images_insert_own on public.generated_images
  for insert with check (user_id = auth.uid());
create policy generated_images_update_own on public.generated_images
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy generated_images_delete_own on public.generated_images
  for delete using (user_id = auth.uid());

create index generated_images_character_created
  on public.generated_images (character_id, created_at desc);
create index generated_images_message
  on public.generated_images (message_id) where message_id is not null;

-- inline_media: which image (or video, later) is attached to a given
-- message. One message may have multiple attached images (future
-- regenerations); `position` lets the feed render in order.
create table public.inline_media (
  id                  uuid primary key default gen_random_uuid(),
  message_id          uuid not null references public.messages(id) on delete cascade,
  generated_image_id  uuid not null references public.generated_images(id) on delete cascade,
  position            integer not null default 0,
  created_at          timestamptz not null default now(),
  unique (message_id, generated_image_id)
);

alter table public.inline_media enable row level security;

create policy inline_media_select_own on public.inline_media
  for select using (message_id in (
    select m.id from public.messages m
      join public.conversations c on c.id = m.conversation_id
     where c.user_id = auth.uid()
  ));
create policy inline_media_insert_own on public.inline_media
  for insert with check (message_id in (
    select m.id from public.messages m
      join public.conversations c on c.id = m.conversation_id
     where c.user_id = auth.uid()
  ));
create policy inline_media_delete_own on public.inline_media
  for delete using (message_id in (
    select m.id from public.messages m
      join public.conversations c on c.id = m.conversation_id
     where c.user_id = auth.uid()
  ));

-- Private bucket for generated bytes. Per-user RLS via first path segment.
insert into storage.buckets (id, name, public)
  values ('generated-media', 'generated-media', false)
  on conflict (id) do nothing;

create policy generated_media_owner_select
  on storage.objects for select
  using (bucket_id = 'generated-media'
         and (storage.foldername(name))[1] = auth.uid()::text);

create policy generated_media_owner_insert
  on storage.objects for insert
  with check (bucket_id = 'generated-media'
              and (storage.foldername(name))[1] = auth.uid()::text);

create policy generated_media_owner_update
  on storage.objects for update
  using (bucket_id = 'generated-media'
         and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'generated-media'
              and (storage.foldername(name))[1] = auth.uid()::text);

create policy generated_media_owner_delete
  on storage.objects for delete
  using (bucket_id = 'generated-media'
         and (storage.foldername(name))[1] = auth.uid()::text);

-- BYOK upsert for the image provider. Parallel to upsert_text_provider
-- (migration 0007). Key is optional — local ComfyUI instances often
-- have no API key.
create or replace function public.upsert_image_provider(
  p_provider_family  text,
  p_base_url         text,
  p_api_key          text,
  p_workflow_config  jsonb
) returns public.provider_configs
language plpgsql
security definer
set search_path = public
as $$
declare
  uid           uuid := auth.uid();
  old_row       public.provider_configs;
  new_secret_id uuid;
  result        public.provider_configs;
  rotating_key  boolean := p_api_key is not null and btrim(p_api_key) <> '';
begin
  if uid is null then raise exception 'auth required'; end if;

  select * into old_row
    from public.provider_configs
    where user_id = uid and kind = 'image' and is_active
    limit 1;

  if rotating_key then
    new_secret_id := vault.create_secret(
      p_api_key,
      format('byok_image_%s_%s', uid, extract(epoch from now())::bigint),
      'BYOK image-provider key (StoryPlots v0)'
    );
    if old_row.vault_secret_id is not null then
      delete from vault.secrets where id = old_row.vault_secret_id;
    end if;
  elsif old_row.id is not null then
    new_secret_id := old_row.vault_secret_id;
  else
    new_secret_id := null;
  end if;

  if old_row.id is not null then
    update public.provider_configs
      set is_active       = true,
          provider_family = p_provider_family,
          base_url        = p_base_url,
          vault_secret_id = new_secret_id,
          workflow_config = p_workflow_config
      where id = old_row.id
      returning * into result;
  else
    insert into public.provider_configs
      (user_id, kind, provider_family, base_url, vault_secret_id,
       workflow_config, is_active)
    values
      (uid, 'image', p_provider_family, p_base_url, new_secret_id,
       p_workflow_config, true)
    returning * into result;
  end if;
  return result;
end;
$$;

grant execute on function public.upsert_image_provider(text, text, text, jsonb) to authenticated;

-- Backend-only; never returned to the client. Parallels get_active_text_key.
create or replace function public.get_active_image_key()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  k text;
begin
  if auth.uid() is null then raise exception 'auth required'; end if;
  select decrypted_secret into k
    from vault.decrypted_secrets
    where id = (
      select vault_secret_id from public.provider_configs
        where user_id = auth.uid() and kind = 'image' and is_active
        limit 1
    );
  return k;
end;
$$;

grant execute on function public.get_active_image_key() to authenticated;
